### ISSUE TITLE
why do u use Session

### ISSUE THREAD

**Issue by HelloTo4x** [vpavic/samples-spring-session#7]
Hi, why do you use Session instead of JWT or Cookie or other authentications... Can u explain me why u choose it, thank u so much

**Comment by vpavic** [comment]
Server-side sessions are still a very valid choice for many applications, especially when coupled with externalized session store which is exactly what Spring Session does for you.

You might want to check out various resources on sessions based vs stateless (JWT) authentication and then decide what fits your use case better:
- https://stackoverflow.com/q/43452896/3944191
- https://stytch.com/blog/jwts-vs-sessions-which-is-right-for-you/
- https://developer.okta.com/blog/2017/08/17/why-jwts-suck-as-session-tokens
